jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run: apt-get install curl
      - run: curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - run: apt-get install nodejs
      - run: cd website && npm install
      - run: cd api/VegaIT.PremestiSE && dotnet restore
      - run: cd api/VegaIT.PremestiSE && dotnet build

  test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run: cd api/VegaIT.PremestiSE && dotnet restore
      - run: cd api/VegaIT.PremestiSE && dotnet test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
